# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mig_error', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b',
            name='a_ptr',
        ),
        migrations.AddField(
            model_name='b',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
